// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_app_analytics: 'enable',
  aws_cloud_logic: 'enable',
  aws_cloud_logic_custom: [
    {
      id: 'mumktf5fmf',
      name: 'production-skedr-api',
      description: '',
      endpoint: 'https://mumktf5fmf.execute-api.eu-west-1.amazonaws.com/production',
      region: 'eu-west-1',
      paths: [
        '/graphiql',
        '/graphql',
        '/oauth',
        '/oauth/callback',
        '/oauth/user',
        '/pool',
        '/search',
        '/suggestion',
        '/tags'
      ]
    },
    {
      name: 'test',
      endpoint: 'http://localhost:1337'
    }
  ],
  aws_cognito_identity_pool_id: 'eu-west-1:69a52460-4ada-4325-b80c-b133c7249428',
  aws_cognito_region: 'eu-west-1',
  aws_content_delivery: 'enable',
  aws_content_delivery_bucket: 'skedriodev-hosting-mobilehub-593289138',
  aws_content_delivery_bucket_region: 'eu-west-1',
  aws_content_delivery_cloudfront: 'enable',
  aws_content_delivery_cloudfront_domain: 'd2s3vlui1moinl.cloudfront.net',
  aws_mobile_analytics_app_id: '567949a6911b4f0494fdec64f964871c',
  aws_mobile_analytics_app_region: 'us-east-1',
  aws_project_id: '1bc53697-6f29-4e1f-a894-60ab870247a3',
  aws_project_name: 'skedr.io-dev',
  aws_project_region: 'eu-west-1',
  aws_resource_name_prefix: 'skedriodev-mobilehub-593289138',
  aws_sign_in_enabled: 'enable',
  aws_user_pools: 'enable',
  aws_user_pools_id: 'eu-west-1_bz5icVezY',
  aws_user_pools_web_client_id: '2apg5ch3tklhv2gr5qc1e26kt9'
}

export default awsmobile
