query autoimportTagList($tags: [String], $count: Int, $nextToken: String) {
  groupTagsList(tags: $tags, count: $count, nextToken: $nextToken) {
    groupTags {
      groupId
      userId
      tags
      preventTrigger
      useAnd
      group {
        id
        groupId
        title
        icon
        poolCount
        photoLimitOptOut
        members
        isMember
        throttleMode
        throttleCount
        throttleRemaining
      }
    }
    nextToken
  }
}
