query autoimportTagList {
  groupTagsList {
    groupId
    userId
    tags
    group {
      id
      groupId
      title
      icon
      poolCount
      photoLimitOptOut
      members
      isMember
      throttleMode
      throttleCount
      throttleRemaining
    }
  }
}
