query userGroups($page: Int!, $perPage: Int!) {
  userGroups(page: $page, perPage: $perPage) {
    page
    pages
    perPage
    total
    groups {
      title
      groupId
      icon
      poolCount
      members
      throttleMode
      throttleCount
      throttleRemaining
      photoLimitOptOut
      photos(perPage: 1, page: 1) {
        dateAdded
      }
    }
  }
}
