 query photos($groupId: ID!) {
  groupPhotos(groupId: $groupId, page: 1, perPage: 20, extras: "views,tags,url_m,url_sq") {
    id
    photoId
    secret
    title
    views
    tags
    urlM
    urlSq
  }
}
