 query userGroup {
  userGroups(page:2, perPage: 10){
    page
    perPage
    total
    groups{
    	name
      groupId
      icon
      poolCount
      members
      throttleMode
      throttleCount
      throttleRemaining
      photoLimitOptOut
    }
  }
}
