query userGroups($page: Int!, $perPage: Int!) {
  userGroups(page: $page, perPage: $perPage) {
    page
    perPage
    total
    groups {
      title
      groupId
      icon
      poolCount
      members
      throttleMode
      throttleCount
      throttleRemaining
      photoLimitOptOut
    }
  }
}
