query groups($userId: ID!, $offset: Int, $count: Int) {
  userGroups(userId: $userId, count: $count, offset: $offset) {
    title
    groupId
    icon
    poolCount
    members
    throttleMode
    throttleCount
    throttleRemaining
    photoLimitOptOut
    photos(first: 1) {
      rawDateAdded
      dateAdded
    }
  }
}
