query groups($userId: ID!, $offset: Int) {
  userGroups(userId: $userId, count: 300, offset: $offset) {
    title
    groupId
    icon
    poolCount
    members
    throttleMode
    throttleCount
    throttleRemaining
    photoLimitOptOut
  }
}
