query userPhotos($userId: ID!, $offset: Int, $count: Int){
  userPhotos(userId: $userId, count: $count, offset: $offset) {
    id
    photoId
    secret
    title
    views
    url_m
    url_sq
  }
}
