query userPhotos($page: Int!, $perPage: Int!) {
  userPhotos(page: $page, perPage: $perPage, extras: "views,tags,url_m,url_sq") {
    total
    pages
    page
    perPage
    photos {
      id
      photoId
      secret
      title
      views
      urlM
      urlSq
      isPublic
      sharedGroups
      totalFavs
    }
  }
}
