query photoTagsList($tags: [String!], $count: Int) {
  photoTagsList(tags: $tags, count: $count) {
    photoId
    photo {
      id
      title
      secret
      farm
      server
      tags
    }
  }
}
