query scheduledPhotos($scheduledAt: String) {
  scheduledPhotos(scheduledAt: $scheduledAt) {
    userId
    groupId
    photoId
    scheduledAt
    photo {
      title
      server
      secret
      farm
      isPublic
    }
    group {
      title
    }
  }
}
