query searchPhotos($perPage: Int!, $page: Int!, $tags: String) {
  searchPhotos(perPage: $perPage, page: $page, tags: $tags) {
    total
    photos {
      photoId
      secret
      farm
      server
    }
  }
}
