query searchGroups($text: String!, $page: Int!, $perPage: Int!, $userId: String, $photoId: String!) {
  searchGroups(text: $text, page: $page, perPage: $perPage, userId: $userId) {
    page
    pages
    groups {
      id
      title
      icon
      poolCount
      photoLimitOptOut
      members
      throttleMode
      throttleCount
      throttleRemaining
      isMember
      rules
      groupTag {
        id
        tags
      }
    }
  }
  photoGroups(photoId: $photoId) {
    id
  }
}
