query searchPhotos($perPage: Int!, $page: Int!, $tags: String, $useAnd: Boolean) {
  searchPhotos(perPage: $perPage, page: $page, tags: $tags, useAnd: $useAnd) {
    total
    photos {
      photoId
      secret
      farm
      server
    }
  }
}
